version: '3.7'

services:
  web:
    build: .
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

#    depends_on:
#      - db
#    env_file:
#      - .env.dev
#  db:
#    image: postgres
#    container_name: db_games
#    volumes:
#      - db_games_vol:/var/lib/postgresql/data
#    env_file:
#      - .env.dev
#    ports:
#      - "5433:5433"
#volumes:
#  db_games_vol:
